name: Build
on:
    push:
        branches: Todo-CICD

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: startsWith(github.event.head_commit.message, 'CICD')
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}
        - name: Build and push backend
          uses: docker/build-push-action@v4
          with:
            context: ./project1-backend
            file: ./project1-backend/Dockerfile
            push: true
            tags: |
                ${{ secrets.DOCKER_HUB_USERNAME }}/wk-registry/todo-backend:latest
        - name: Build and push frontend
          uses: docker/build-push-action@v4
          with:
            context: ./project1-frontend
            file: ./project1-frontend/Dockerfile
            push: true
            tags: |
                ${{ secrets.DOCKER_HUB_USERNAME }}/wk-registry/todo-frontend:latest