name: Build
on:
    push:
        branches: Todo-CICD

# This workflow builds and deploys the project to Docker Hub and Azure VM

jobs:
    deploy-to-dockerhub:
        runs-on: ubuntu-latest
        if: startsWith(github.event.head_commit.message, 'CICD')
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}
        - name: Build and push backend
          uses: docker/build-push-action@v4
          with:
            context: ./project1-backend
            file: ./project1-backend/Dockerfile
            push: true
            tags: |
                ${{ secrets.DOCKER_HUB_USERNAME }}/wk-registry:todo-backend
        - name: Build and push frontend
          uses: docker/build-push-action@v4
          with:
            context: ./project1-react
            file: ./project1-react/Dockerfile
            push: true
            tags: |
                ${{ secrets.DOCKER_HUB_USERNAME }}/wk-registry:todo-frontend

    deploy-to-azure:
        runs-on: ubuntu-latest
        needs: deploy-to-dockerhub
        if: startsWith(github.event.head_commit.message, 'CICD')
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Create backend .env
          run: |
            echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' > backend.env
            echo 'SECRET_KEY=${{ secrets.JWT_KEY }}' >> backend.env

        - name: Create frontend .env
          run: |
            echo "REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}" > frontend.env

        - name: Copy .env files to VM
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ secrets.AZURE_VM_IP }}
            username: azureuser
            key: ${{ secrets.AZURE_VM_SSH_KEY }}
            source: "backend.env,frontend.env"
            target: "~/"

        - name: Deploy containers on VM
          uses: appleboy/ssh-action@v0.1.10
          with:
            host: ${{ secrets.AZURE_VM_IP }}
            username: azureuser
            key: ${{ secrets.AZURE_VM_SSH_KEY }}
            script: |
              docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/wk-registry:todo-backend
              docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/wk-registry:todo-frontend
              docker stop backend || true && docker rm backend || true
              docker stop frontend || true && docker rm frontend || true
              docker run -d \
                -v ~/backend.env:/app/.env \
                --name backend \
                -p 9000:9000 \
                ${{ secrets.DOCKER_HUB_USERNAME }}/wk-registry:todo-backend
              docker run -d \
                -v ~/frontend.env:/app/.env \
                --name frontend \
                -p 3000:3000 \
                ${{ secrets.DOCKER_HUB_USERNAME }}/wk-registry:todo-frontend
